on: [push, pull_request]
name: Test
jobs:
  test:
    name: Ubuntu on node ${{ matrix.node }}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        os: [ubuntu-18.04]
        node: [16]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
            
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.28.0
          run_install: |
            - recursive: false
      - run: pnpm run check
