on: [push, pull_request]
name: Test
jobs:
  test:
    name: Ubuntu on node ${{ matrix.node }}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        os: [ubuntu-18.04]
        node: [12, 13]
    steps:
      - uses: actions/checkout@v2
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.0.2
          run_install: true
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: pnpm i
      - run: pnpm run check
