on: [push, pull_request]
name: Test
jobs:
  test:
    name: Ubuntu on node ${{ matrix.node }}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        os: [ubuntu-18.04]
        node: [12, 13]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install -g pnpm
      - run: pnpm i
      - run: pnpm run check
