on: [push, pull_request]
name: Test & Lint
jobs:
  test:
    name: Ubuntu on Node ${{ matrix.node }}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        os: [ubuntu-18.04]
        node: [15, 16]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.28.0
          run_install: |
            - recursive: false
      - run: pnpm run check
